# Generated by Django 5.2.13 on 2026-04-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('t1', models.FloatField(blank=True, null=True)),
                ('h1', models.FloatField(blank=True, null=True)),
                ('t2', models.FloatField(blank=True, null=True)),
                ('h2', models.FloatField(blank=True, null=True)),
                ('t3', models.FloatField(blank=True, null=True)),
                ('h3', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorNameSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('t1_name', models.CharField(blank=True, default='T1', max_length=100)),
                ('h1_name', models.CharField(blank=True, default='H1', max_length=100)),
                ('t2_name', models.CharField(blank=True, default='T2', max_length=100)),
                ('h2_name', models.CharField(blank=True, default='H2', max_length=100)),
                ('t3_name', models.CharField(blank=True, default='T3', max_length=100)),
                ('h3_name', models.CharField(blank=True, default='H3', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('sensor', models.CharField(choices=[('t1', 'Hőmérséklet 1'), ('h1', 'Páratartalom 1'), ('t2', 'Hőmérséklet 2'), ('h2', 'Páratartalom 2'), ('t3', 'Hőmérséklet 3'), ('h3', 'Páratartalom 3')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('device_id', 'sensor', 'email')},
            },
        ),
        migrations.CreateModel(
            name='AlertStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('sensor', models.CharField(choices=[('t1', 'Hőmérséklet 1'), ('h1', 'Páratartalom 1'), ('t2', 'Hőmérséklet 2'), ('h2', 'Páratartalom 2'), ('t3', 'Hőmérséklet 3'), ('h3', 'Páratartalom 3')], max_length=10)),
                ('is_alerted', models.BooleanField(default=False)),
                ('last_alert_time', models.DateTimeField(blank=True, null=True)),
                ('last_reset_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('device_id', 'sensor')},
            },
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('sensor', models.CharField(choices=[('t1', 'Hőmérséklet 1'), ('h1', 'Páratartalom 1'), ('t2', 'Hőmérséklet 2'), ('h2', 'Páratartalom 2'), ('t3', 'Hőmérséklet 3'), ('h3', 'Páratartalom 3')], max_length=10)),
                ('threshold_value', models.FloatField()),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('device_id', 'sensor')},
            },
        ),
    ]
