# Generated by Django 5.0.6 on 2026-06-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_create_sensornameset'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrecipient',
            name='ntfy',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
